version: '3.8'

services:
  ai-service:
    build:
      context: ./ai-engine
    container_name: falci-ai-engine
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - falci-net
    restart: unless-stopped

  gateway-service:
    build:
      context: ./gateway
    container_name: falci-gateway
    ports:
      - "39842:8000"
    environment:
      - AI_SERVICE_URL=http://falci-ai-engine:8000/predict
    volumes:
      - shared-audio:/shared/audio
    networks:
      - falci-net
    depends_on:
      - ai-service
    restart: unless-stopped

networks:
  falci-net:
    driver: bridge

volumes:
  shared-audio: